{
  "hash": "766b48dea9a0f92fc8b2aaef09735c0d",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Assignment 2: Who Do We Know the Least About?\"\nsubtitle: \"Measuring uncertainty in American Community Survey data\"\nauthor: \"Gil Rezin\"\ndate: today\nformat:\n  html:\n    toc: true\n    code-fold: false\nexecute:\n  warning: false\n  message: false\n---\n\n## Setup\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(tidycensus)\n```\n:::\n\n\n---\n\n## The question\n\nEvery number the American Community Survey publishes is an estimate drawn from a\nsample, not a count. That means every number comes with a margin of error — a\nstatement about how wrong it might be.\n\nMost people ignore it. In this assignment, you won't.\n\n**In this analysis, I look at median age across counties in Washington State, and\nask which communities we measure most and least reliably. Median age is a useful metric to policymakers, as it can be used in determining funding for state programs such as youth or senior programs.**\n\n---\n\n## Choosing what to measure\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmy_state <- \"WA\"        # two-letter abbreviation, in quotes\nmy_variable <- \"B01002_001\"     # the variable code, in quotes\n```\n:::\n\n\n## Pulling the data\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_data <- get_acs(\n  geography = \"county\",\n  variables = my_variable,\n  state = my_state,\n  year = 2023,\n  survey = \"acs5\"\n)\n```\n:::\n\n\nLet's look at what came back.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndim(county_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 39  5\n```\n\n\n:::\n\n```{.r .cell-code}\nhead(county_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 5\n  GEOID NAME                       variable   estimate   moe\n  <chr> <chr>                      <chr>         <dbl> <dbl>\n1 53001 Adams County, Washington   B01002_001     29.2   0.3\n2 53003 Asotin County, Washington  B01002_001     45.5   0.6\n3 53005 Benton County, Washington  B01002_001     36.2   0.2\n4 53007 Chelan County, Washington  B01002_001     40.4   0.4\n5 53009 Clallam County, Washington B01002_001     51.8   0.3\n6 53011 Clark County, Washington   B01002_001     38.9   0.2\n```\n\n\n:::\n:::\n\n\n**There are 39 counties in Washington. Therefore, our query returned 39 rows: one per county.**\n\n---\n\n## How big is the margin of error?\n\nA margin of error of 3,000 means something very different for an estimate of 20,000\nthan for an estimate of 200,000. To compare across places, we need it as a\npercentage.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_data <- county_data %>%\n  mutate(moe_pct = moe / estimate * 100)\n```\n:::\n\n\nNow sort to see which counties are measured least reliably.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_data %>%\n  arrange(desc(moe_pct)) %>%\n  select(NAME, estimate, moe, moe_pct) %>%\n  head(10)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 10 × 4\n   NAME                           estimate   moe moe_pct\n   <chr>                             <dbl> <dbl>   <dbl>\n 1 Garfield County, Washington        52.6   4.3    8.17\n 2 Wahkiakum County, Washington       54.8   2.2    4.01\n 3 Columbia County, Washington        52.1   1.9    3.65\n 4 Douglas County, Washington         38.4   1      2.60\n 5 Skamania County, Washington        48.6   1      2.06\n 6 Kittitas County, Washington        37.9   0.7    1.85\n 7 Walla Walla County, Washington     38.3   0.6    1.57\n 8 Whitman County, Washington         26.1   0.4    1.53\n 9 Ferry County, Washington           52.8   0.7    1.33\n10 Asotin County, Washington          45.5   0.6    1.32\n```\n\n\n:::\n:::\n\n\n**Garfield County has the least reliable estimate, with a margin of error of 8.17%.**\n\n---\n\n## Sorting counties into reliability categories\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_data <- county_data %>%\n  mutate(reliability = case_when(\n    moe_pct < 3  ~ \"High confidence\",\n    moe_pct < 6 ~ \"Moderate\",\n    TRUE         ~ \"Low confidence\"\n  ))\n\ncount(county_data, reliability)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 2\n  reliability         n\n  <chr>           <int>\n1 High confidence    36\n2 Low confidence      1\n3 Moderate            2\n```\n\n\n:::\n:::\n\n\n**Assuming that a high confidence lies with less than 3 percent MOE, 36/39 counties are classified as \"High confidence\". Of the remaining three, just Garfield County is of Low confidence (>6% MOE). The two remaining counties are of moderate confidence.**\n\n---\n\n## Is the margin of error bigger in small places?\n\nTo answer this we need population and our variable side by side, in the same row.\nThat means a **wide** pull.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_wide <- get_acs(\n  geography = \"county\",\n  variables = c(myvar = my_variable,\n                pop   = \"B01003_001\"),\n  state = my_state,\n  year = 2023,\n  survey = \"acs5\",\n  output = \"wide\"\n)\n\nhead(county_wide)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 6\n  GEOID NAME                       myvarE myvarM   popE  popM\n  <chr> <chr>                       <dbl>  <dbl>  <dbl> <dbl>\n1 53001 Adams County, Washington     29.2    0.3  20690    NA\n2 53003 Asotin County, Washington    45.5    0.6  22424    NA\n3 53005 Benton County, Washington    36.2    0.2 210224    NA\n4 53007 Chelan County, Washington    40.4    0.4  79518    NA\n5 53009 Clallam County, Washington   51.8    0.3  77593    NA\n6 53011 Clark County, Washington     38.9    0.2 510516    NA\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_wide <- county_wide %>%\n  mutate(moe_pct = myvarM / myvarE * 100) %>%\n  mutate(reliability = case_when(\n    moe_pct < 3  ~ \"High confidence\",\n    moe_pct < 6 ~ \"Moderate\",\n    TRUE         ~ \"Low confidence\"\n  ))\n```\n:::\n\n\nNow compare the average population of counties in each reliability category.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_wide %>%\n  group_by(reliability) %>%\n  summarize(\n    n_counties = n(),\n    avg_population = mean(popE)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 3\n  reliability     n_counties avg_population\n  <chr>                <int>          <dbl>\n1 High confidence         36        214725.\n2 Low confidence           1          2326 \n3 Moderate                 2          4284.\n```\n\n\n:::\n:::\n\n\n**The average population of high-confidence counties is significantly higher than that of low and moderate-confidence counties. Similarly, moderate-confidence counties have higher populations than low-confidence counties. Thus, there appears to exist a direct linear relationship between a county's population and MOE confidence.**\n\n---\n\n## What this means for policy\n\n**As a result of high margins of error, we know the least about the least populous counties in Washington state: Garfield, Wahkiakum, and Columbia counties. Due to its high margin of error, Garfield County has a median age of 52.6 +/- 8.17%. This means that the actual median age of Garfield County is anywhere between 48.3 and 56.9. This is a very wide range, the reason of which comes from the way the ACS works in practice. The 5-year ACS (American Community Survey) is a survey run by the United States Census Bureau that samples approximately 3.5% of the US population per survey conducted. As this is a sample, smaller regions will have less respondents relative to more populous regions. For example, Grant County, WA (population 100,428) would have an approximate sample size of 3,515 people; this yields an MOE of 0.9%. By contrast, a much smaller county such as Columbia County, WA (population 3,996) would only have an approximate sample size of 140 people; this yields in an MOE of 3.6%. When less individuals are sampled overall across a geographic area, the overall result has increased sampling variability, increasing the overall margin of error. This can have downstream effects for policymakers: to not know with accuracy the median age of a county, for example, can result in incorrect funding for schools (hurting younger individuals) or senior support programs (older individuals).**\n\n---\n\n## Optional challenges - For those craving more\n\n---\n\n## Before you submit\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}